import type { Metadata } from 'next';
import { Inter, Source_Serif_4, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { Header, HeaderStickyScroll } from '@/components/molecules/header';
import { Footer } from '@/components/molecules/footer';

const fontInter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const fontSourceSerif = Source_Serif_4({
  variable: '--font-source-serif',
  subsets: ['latin'],
});

const fontJetbrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Meal App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontInter.variable} ${fontSourceSerif.variable} ${fontJetbrainsMono} h-full overflow-x-hidden antialiased`}
      data-scroll-behavior="smooth"
      suppressHydrationWarning
    >
      <body className="flex min-h-svh flex-col items-stretch">
        <HeaderStickyScroll>
          <Header />
        </HeaderStickyScroll>
        {children}
        <Footer />
      </body>
    </html>
  );
}
